###
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "O Hobbit",
  "author": "J.R.R.Tolkien",
  "description": "Um hobbit é uma das criaturas criadas por J. R. R. Tolkien em suas obras (notavelmente O Hobbit e O Senhor dos Anéis), onde têm um papel principal, apesar de à partida serem um povo secundário entre os que habitam a Terra Média."
}

###
GET http://localhost:3000/books
Accept: application/json

###
GET http://localhost:3000/books/12
Accept: application/json

###
PUT http://localhost:3000/books/3
Content-Type: application/json

{
  "title": "Sherlock Holmes",
  "author": "Arthur Conan Doyle",
  "description": "Segundo Conan Doyle, criador do personagem, Sherlock Holmes viveu em Londres, no apartamento 221B Baker Street, entre os anos 1881 e 1903, durante o último período da Era Vitoriana, onde passou muitos anos na companhia do seu amigo e colega, Dr. Watson. Hoje, esse endereço é um museu dedicado a Sherlock Holmes."
}

###
DELETE http://localhost:3000/books/12
Accept: application/json
